version: '3.1'

volumes:
  waiterapp-mongo:
    driver: local

services:
  base: &base
    hostname: waiterapp_base
    image: node:18.12.1-alpine
    ports: []
    stdin_open: true
    tty: true
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app

  mongo:
    hostname: waiterapp_mongo
    container_name: waiterapp_mongo
    image: mongo:6.0.3
    volumes:
      - waiterapp-mongo:/data/mongo
    ports:
      - 27017:27017

  app: &app
    <<: *base
    hostname: waiterapp_app
    command: yarn dev
    env_file:
      - .env
    environment:
      EXPRESS_PORT: ${ENV_EXPRESS_PORT:-3001}
    ports:
      - ${ENV_EXPRESS_PORT:-3001}:${ENV_EXPRESS_PORT:-3001}
    depends_on:
      - mongo
